name: Merge Upstream into Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Fork
        uses: actions/checkout@v2
        with:
          repository: SubhamSubhasisPatra/Watusi-for-WhatsApp  # Replace with your fork's repository
          ref: master  # Replace with the default branch of your fork if not master

      - name: Configure Git
        run: |
          git config --global user.name "subhamsubhasispatra"
          git config --global user.email "subhasispatra94@gmail.com"

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/FouadRaheb/Watusi-for-WhatsApp.git
          git fetch upstream

      - name: Merge Changes from Upstream
        run: |
          git merge upstream/master --allow-unrelated-histories
